Responsive About Us
JaMR94/JaMR94.github.io pull request #109
Opened 2023-03-16 02:24 UTC by kareng13

Se hizo responsive del about

2023-03-16 14:35 UTC, Pudin-con-pasas-uwu submitted a review, later dismissed

2023-03-16 15:07 UTC, Creaky27 submitted a review, later dismissed

2023-03-16 15:45 UTC, GerardoCasC requested changes
Falta centrar los el texto de "This is..." y aumentar el width de "our philosophy"
Y el texto debajo de About us reducele el width <3

2023-03-16 22:32 UTC, lokilaufeysonXD submitted a review, later dismissed

2023-03-17 00:56 UTC, GerardoCasC approved these changes

2023-03-17 01:59 UTC, EdgarPerez07 approved these changes
Bien

2023-03-17 03:27 UTC, merged